### ISSUE TITLE
Profiling a single class taking extraordinarily long time

### ISSUE THREAD

**Issue by exabrial** [visualvm/visualvm.github.io#1]
I put a single class from my application (< 200 LOC, 15 methods that do nothing but interaction with collections and some reflection) into the profiler roots box, and in the "Profile Only Class" I put that class's package. Profile new runnables is unchecked.

VisualVM is taking a _massive_ amount of time at the "profiler busy" progress bar. I have a feeling that the class filter is not working properly.

**Comment by cowwoc** [comment]
@exabrial You reported this bug against the wrong project. You should report this against https://github.com/oracle/visualvm

**Comment by exabrial** [comment]
thanks
